#!/bin/bash


_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $HELL_REPO == "TALENTED-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9NSUtBU0EtVVNFUkJPVC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $HELL_REPO == "TALENTED-BOT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9NSUtBU0EtVVNFUkJPVC9hcmNoaXZlL21haW4uemlw" | base64 -d
    elif [[ $HELL_REPO =~ $regex ]]
    then
        if [[ $HELL_REPO_BRANCH ]]
        then
            echo "${HELL_REPO}/archive/${HELL_REPO_BRANCH}.zip"
        else
            echo "${HELL_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL0RFQURMWS1GSUdIVEVSUy9NSUtBU0EtVVNFUkJPVC9hcmNoaXZlL21haW4uemlw" | base64 -d
    fi
}


start_bot () {
    local zippath
    zippath="TalentedBot.zip"
    echo "  Downloading source code ..."
    wget -q $(_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    DEADLYPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "  Processing Codes..."
    rm -rf "$zippath"
    sleep 5
    cd $TALENTEDPATH
    echo "  • Starting Talented Bot •  "

    python3 ../setup/updater.py ../requirements.txt requirements.txt
    python3 -m talentedBot
}

start_bot
